name: w bullshit

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn

      - name: Generate
        run: |
          git config --local user.email "2107795244@qq.com"
          git config --local user.name "www159"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB }}@github.com/${{ github.repository }}
          git pull --rebase
          node index.js
          git commit -am "new bullshit comes"
          git push
